name: Build Full Project
on: [push]
jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          pip install pyinstaller pywebview

      - name: Create Entry Script
        shell: pwsh
        run: |
          $code = @"
          import webview
          import os
          import sys

          def resource_path(relative_path):
              if hasattr(sys, '_MEIPASS'):
                  return os.path.join(sys._MEIPASS, relative_path)
              return os.path.join(os.path.abspath("."), relative_path)

          html_path = resource_path('index.html')
          webview.create_window('REDLINE ARCHITECT', html_path)
          webview.start()
          "@
          $code | Out-File -FilePath main.py -Encoding utf8

      - name: Compile EXE
        run: |
          pyinstaller --noconsole --onefile --icon=REDLINE.ico --add-data ".;." main.py

      - name: Upload Result
        uses: actions/upload-artifact@v4
        with:
          name: Redline-Full-Package
          path: dist/*.exe
